### ISSUE TITLE
Add more programs in python

### ISSUE THREAD

**Issue by nirajpdn** [1teacher1/Hacktoberfest2022#3]

**Comment by JoydeepMallick** [comment]
I would like to work on this issue.

**Comment by SanskarJain007** [comment]
Assign this to me

**Comment by nirajpdn** [comment]
@SanskarJain007 @JoydeepMallick , no need to assign here. You can create separate `Python` folder and add programs.
You can mention issues in the comment while submitting pull request.
Go ahead guys.

**Comment by OjaswiPande** [comment]
I added a file of binary search. Can you check once?
