### ISSUE TITLE
Add more programs in go

### ISSUE THREAD

**Issue by nirajpdn** [1teacher1/Hacktoberfest2022#4]

**Comment by Ivar246** [comment]
please assign me this.

**Comment by nirajpdn** [comment]
> please assign me this.

No need to assign. Just add programs in separate folder wise and mention this issue in pull request.

**Comment by devkishor8007** [comment]
@nirajpdn hello, I have done - please have a look: https://github.com/1teacher1/Hacktoberfest2022/pull/35
